// src/app/(frontend-user-external)/toolbox/skindrop/page.tsx
"use client";

import { Radix } from "@/components";
import { copyToClipboard } from "@/lib/utils";
import { LoaderCircleIcon } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { SkinViewer, WalkingAnimation } from "skinview3d";

export default function SkinDrop() {
    const [step, setStep] = useState(1);

    const [file, setFile] = useState<File | null>(null);
    const [url, setUrl] = useState("");
    const [playerName, setPlayerName] = useState<string>("");

    const canvasRef = useRef<HTMLCanvasElement>(null);
    const skinViewerRef = useRef<SkinViewer | null>(null);
    const skinBlobRef = useRef<Blob | null>(null);

    const [uploadSuccess, setUploadSuccess] = useState<boolean>(true);
    const [errorMessage, setErrorMessage] = useState<string>("");
    const [s3Filename, setS3Filename] = useState<string>("");

    const [copied, setCopied] = useState<boolean>(false);

    const validStep1 = useMemo(() => {
        return !!file || !!url;
    }, [file, url]);

    const validStep2 = useMemo(() => {
        return playerName.length >= 3 && playerName.length <= 16 && /^[a-zA-Z][a-zA-Z0-9_]+$/.test(playerName);
    }, [playerName]);

    const handleFile = (f: File | null) => {
        if (!f) {
            setFile(null); // 清空文件
            return;
        }
        if (!f.type.startsWith("image/")) {
            alert("必须是图片文件");
            return;
        }
        setFile(f);
    };

    const createSkinViewer = useCallback(async () => {
        if (!canvasRef.current) return;
        // 清理旧实例
        if (skinViewerRef.current) {
            skinViewerRef.current.dispose();
            skinViewerRef.current = null;
        }
        let skinUrl: string;
        if (file) {
            skinBlobRef.current = file;
            skinUrl = URL.createObjectURL(file);
        } else if (url) {
            try {
                const res = await fetch(`/api/skindrop/download?id=${url.split("/").pop()}`);
                const blob = await res.blob();
                skinBlobRef.current = blob;
                skinUrl = URL.createObjectURL(blob);
            } catch (err) {
                console.error("获取 NameMC 皮肤失败", err);
                return;
            }
        } else {
            return;
        }
        skinViewerRef.current = new SkinViewer({
            canvas: canvasRef.current,
            width: 368,
            height: 368,
            skin: skinUrl,
        });
        skinViewerRef.current.animation = new WalkingAnimation();
    }, [file, url]);

    useEffect(() => {
        if (step === 1) {
            if (skinViewerRef.current) {
                skinViewerRef.current.dispose();
                skinViewerRef.current = null;
            }
        }

        if (step === 2) {
            createSkinViewer();
        }

        if (step === 3) {
            const upload = async () => {
                if (!skinBlobRef.current) return;
                const formData = new FormData();
                formData.append("file", skinBlobRef.current as Blob, file?.name || "");
                const extension = file ? file.name.split(".").pop() : "png";
                const filename = encodeURIComponent(`${playerName}.${extension}`);
                setS3Filename(filename);
                try {
                    const res = await fetch(`/api/skindrop/upload/${filename}`, {
                        method: "POST",
                        body: formData,
                    });
                    if (!res.ok) {
                        throw new Error(await res.text());
                    }
                    setUploadSuccess(true);
                    setErrorMessage("");
                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                } catch (error: any) {
                    setUploadSuccess(false);
                    setErrorMessage(error?.data?.statusMessage || error?.message || "上传失败");
                } finally {
                    // 跳转到完成页
                    setStep(4);
                }
            };
            upload();
        }

        if (step === 5) {
            setFile(null);
            setUrl("");
            setPlayerName("");
            setUploadSuccess(true);
            setErrorMessage("");
            setS3Filename("");
            setStep(1); // 重置流程
        }
    }, [step, file, url, createSkinViewer, playerName]);

    return (
        <main className="pixel-font flex h-[calc(100vh-61px)] w-full translate-y-15.25 flex-col items-center justify-center">
            <h1 className="text-4xl font-bold">换皮肤工具</h1>

            <div className="mt-12 grid h-84 w-4xl grid-cols-5 gap-x-6">
                {/* 预览 */}
                <Radix.Card className="col-span-2">
                    <Radix.CardHeader>
                        <Radix.CardTitle>预览</Radix.CardTitle>
                    </Radix.CardHeader>
                    <Radix.CardContent className="flex h-full items-center justify-center">
                        {step === 1 ? (
                            <div className="text-muted-foreground text-center">
                                上传皮肤后
                                <br />
                                此处将显示预览
                            </div>
                        ) : (
                            <canvas ref={canvasRef} className="-translate-y-6 bg-transparent" width={256} height={256} />
                        )}
                    </Radix.CardContent>
                </Radix.Card>

                {/* 上传 */}
                <Radix.Card className="col-span-3">
                    <Radix.CardHeader>
                        <Radix.CardTitle>上传</Radix.CardTitle>
                    </Radix.CardHeader>
                    <Radix.CardContent className="h-full">
                        {step === 1 && (
                            <div className="flex h-full flex-col gap-6">
                                <div className="mt-4 mb-auto flex h-full flex-col justify-center gap-4">
                                    {/* 文件 */}
                                    {url.length === 0 && (
                                        <div className="grid gap-2">
                                            <Radix.Label htmlFor="skinblob">上传皮肤文件</Radix.Label>
                                            <Radix.Input
                                                id="skinblob"
                                                type="file"
                                                accept="image/png,.png"
                                                onChange={(e) => handleFile(e.target.files?.[0] ?? null)}
                                            />
                                        </div>
                                    )}

                                    {/* URL */}
                                    {file === null && (
                                        <div className="grid gap-2">
                                            <Radix.Label htmlFor="skinurl">或者输入图片 URL</Radix.Label>
                                            <Radix.Input
                                                id="skinurl"
                                                type="url"
                                                placeholder="https://namemc.com/skin/... 或 https://zh.namemc.com/skin/..."
                                                value={url}
                                                onChange={(e) => {
                                                    setUrl(e.target.value);
                                                }}
                                            />
                                        </div>
                                    )}
                                </div>

                                <Radix.Separator className="mt-auto" />

                                <Radix.Button className="ml-auto w-fit px-4" disabled={!validStep1} onClick={() => setStep(2)}>
                                    下一步
                                </Radix.Button>
                            </div>
                        )}

                        {step === 2 && (
                            <div className="flex h-full flex-col gap-6">
                                <div className="my-auto w-full space-y-2 px-2">
                                    <p className="text-base font-medium">这是你要的皮肤吗？</p>
                                    <p className="text-muted-foreground text-sm">如果是，请输入您的游戏 ID</p>
                                    <Radix.Input
                                        placeholder="例如: LingyunAwA"
                                        value={playerName}
                                        onChange={(e) => setPlayerName(e.target.value)}
                                        className="w-full text-lg"
                                    />
                                </div>
                                <Radix.Separator className="mt-auto" />

                                <Radix.Button className="ml-auto w-fit px-4" disabled={!validStep2} onClick={() => setStep(3)}>
                                    下一步
                                </Radix.Button>
                            </div>
                        )}

                        {step === 3 && (
                            <div className="flex h-full -translate-x-0.5 flex-col items-center justify-center gap-4">
                                <LoaderCircleIcon className="-translate-x-1.25 animate-spin" />
                                <p className="text-muted-foreground">正在上传...</p>
                            </div>
                        )}

                        {step === 4 && (
                            <div className="flex h-full w-full flex-col justify-center gap-4">
                                {uploadSuccess ? (
                                    <Radix.Alert variant="default" className="my-auto bg-green-500/25">
                                        <Radix.AlertTitle>上传成功！</Radix.AlertTitle>
                                        <Radix.AlertDescription>您的皮肤已成功上传至服务器。</Radix.AlertDescription>
                                    </Radix.Alert>
                                ) : (
                                    <Radix.Alert variant="destructive">
                                        <Radix.AlertTitle>上传失败</Radix.AlertTitle>
                                        <Radix.AlertDescription>
                                            {errorMessage}
                                            <br />
                                            如需帮助，请复制错误信息并发给站点管理员 LingyunAwA
                                        </Radix.AlertDescription>
                                    </Radix.Alert>
                                )}

                                {uploadSuccess && (
                                    <div className="grid grid-cols-5 gap-2">
                                        <Radix.Button
                                            variant="outline"
                                            onClick={() => {
                                                setStep(5);
                                            }}>
                                            再次上传
                                        </Radix.Button>
                                        <Radix.Button
                                            onClick={() => {
                                                setCopied(true);
                                                copyToClipboard(
                                                    `/skin url https://a7zzsqcyurqyggvo.public.blob.vercel-storage.com/SkinDrop/${s3Filename}`
                                                );
                                                setTimeout(() => {
                                                    setCopied(false);
                                                }, 2000);
                                            }}
                                            className="col-span-4">
                                            {copied ? "已复制" : "复制换肤命令"}
                                        </Radix.Button>
                                    </div>
                                )}

                                {!uploadSuccess && (
                                    <div className="grid grid-cols-5 gap-2">
                                        <Radix.Button
                                            variant="outline"
                                            onClick={() => {
                                                setStep(5);
                                            }}>
                                            再次上传
                                        </Radix.Button>
                                        <Radix.Button
                                            onClick={() => {
                                                setCopied(true);
                                                copyToClipboard(errorMessage);
                                                setTimeout(() => {
                                                    setCopied(false);
                                                }, 2000);
                                            }}
                                            className="col-span-4">
                                            {copied ? "已复制" : "复制错误信息"}
                                        </Radix.Button>
                                    </div>
                                )}
                            </div>
                        )}
                    </Radix.CardContent>
                </Radix.Card>
            </div>
        </main>
    );
}

// app/pages/utils/skindrop.vue
<script setup lang="ts">
    import { SkinViewer, WalkingAnimation } from "skinview3d";
    import SplitText from "~/components/vuebits/animations/SplitText.vue";
    import type { IWrappedAnimatedContent } from "~/components/WrappedAnimatedContent.vue";

    const ani1 = ref<IWrappedAnimatedContent>();
    const ani2 = ref<IWrappedAnimatedContent>();

    onMounted(() => {
        ani1.value?.animating();
    });

    // Global
    const skinFile = ref<Blob | null>(null);

    // Step Control
    const step = ref<number>(1);
    const nextStep = () => step.value++;
    const previousStep = () => step.value--;
    const steps = ["选择", "确认", "上传", "完成"];

    // Skin Preview
    const skinview = ref<HTMLCanvasElement | null>(null);
    const skinviewInstance = ref<SkinViewer | null>(null);

    // Step Change Control
    const s3_filename = ref<string>("");
    const s4_success = ref<boolean>(true);
    const s4_fail_msg = ref<string>("");
    watch(step, async (newValue) => {
        if (newValue === 1) {
            s1_input_a.value = null;
            s1_input_b.value = "";
            s2_input.value = "";
            skinviewInstance.value?.dispose();
            skinviewInstance.value = null;
        }
        if (newValue === 2) {
            const _type = s1_input_a.value ? "file" : "url";
            switch (_type) {
                case "file":
                    if (s1_input_a.value) {
                        skinFile.value = new Blob([s1_input_a.value], { type: s1_input_a.value.type });
                    }
                    break;
                case "url":
                    skinFile.value = await $fetch<Blob>("/api/proxy/namemc/" + s1_input_b.value.split("/").pop());
                    break;
            }
            nextTick(() => {
                if (!skinviewInstance.value) {
                    skinviewInstance.value = new SkinViewer({
                        canvas: skinview.value!,
                        width: 368,
                        height: 368,
                        skin: URL.createObjectURL(skinFile.value as File),
                    });
                }
                skinviewInstance.value.animation = new WalkingAnimation();
            });
        }
        if (newValue === 3) {
            console.log(skinFile.value);
            if (!skinFile.value) {
                return;
            }
            const formData = new FormData();
            formData.append("file", skinFile.value);
            if (skinFile.value instanceof File) {
                s3_filename.value = encodeURIComponent(`${s2_input.value}.${skinFile.value.name.split(".").pop()}`);
            } else {
                s3_filename.value = encodeURIComponent(`${s2_input.value}.png`);
            }
            try {
                // 3. 调用我们自己的后端接口
                await $fetch(`/api/alist/upload/${s3_filename.value}`, {
                    method: "POST",
                    body: formData,
                });
                s4_fail_msg.value = "";
            } catch (error: any) {
                s4_success.value = false;
                s4_fail_msg.value = error.data?.statusMessage || error.message;
            } finally {
                step.value = 4;
            }
        }
        if (newValue === 5) {
            step.value = 1;
        }
    });

    // Inputs
    const s1_input_a = ref<File | null>(null);
    const s1_input_b = ref<string>("");
    function onFileChange(e: Event) {
        const target = e.target as HTMLInputElement;
        s1_input_a.value = target.files ? target.files[0]! : null;
    }
    const s2_input = ref<string>("");

    // Locks
    const s1_lock_a = ref<boolean>(false);
    const s1_lock_b = ref<boolean>(false);
    watch(s1_input_a, (newValue) => {
        s1_lock_b.value = newValue !== null;
    });
    watch(s1_input_b, (newValue) => {
        s1_lock_a.value = newValue !== "";
    });

    // Validators
    const s1_valid = ref<boolean>(false);
    const _validateUrl = (url: string) => {
        return url.startsWith("https://namemc.com/skin/") || url.startsWith("https://zh.namemc.com/skin/");
    };
    watch([s1_input_a, s1_input_b], ([newValue_a, newValue_b]) => {
        s1_valid.value = (newValue_a !== null || (newValue_b !== "" && _validateUrl(newValue_b))) && !(newValue_a !== null && newValue_b !== "");
    });
    const s2_valid = ref<boolean>(false);
    const _validateName = (name: string) => {
        return name.length >= 3 && name.length <= 16 && /^[a-zA-Z][a-zA-Z0-9_]+$/.test(name);
    };
    watch(s2_input, (newValue) => {
        s2_valid.value = newValue !== "" && _validateName(newValue);
    });

    const copyCmd = () => {
        copy(`${useRuntimeConfig().public.alistUrl}/d/SkinDrop/${s3_filename.value}`);
    };
</script>

<template>
    <div class="hero min-h-screen">
        <div class="hero-overlay"></div>
        <div class="hero-content text-neutral-content w-full max-w-7xl flex-col">
            <div class="w-5xl">
                <WrappedAnimatedContent ref="ani1" manual @complete="ani2?.animating()">
                    <SplitText
                        text="落颜 · SkinDrop | 轻量级换皮肤工具"
                        className="font-semibold text-center text-2xl lg:text-[1.5vw]"
                        :delay="15"
                        :duration="0.5"
                        ease="power3.out"
                        split-type="chars"
                        :from="{ opacity: 0, y: 40 }"
                        :to="{ opacity: 1, y: 0 }"
                        :threshold="0.1"
                        root-margin="-100px"
                        text-align="center" />
                </WrappedAnimatedContent>
                <br />
                <WrappedAnimatedContent ref="ani2" class="w-full" manual :delay="0.25">
                    <div class="w-full grid grid-cols-5 grid-rows-1 gap-x-4">
                        <div class="card card-border bg-base-100 aspect-square w-full col-span-2">
                            <div class="card-body flex justify-center items-center">
                                <div class="skeleton w-36 h-64" v-if="step === 1"></div>
                                <canvas ref="skinview" class="bg-base-100 size-64" v-else />
                            </div>
                        </div>
                        <div class="card card-border bg-base-100 w-full col-span-3">
                            <div class="card-body">
                                <ul class="steps h-1/4">
                                    <li class="step" :class="{ 'step-primary': step >= index + 1 }" v-for="(content, index) in steps" :key="content">
                                        {{ content }}
                                    </li>
                                </ul>

                                <section class="w-full h-full flex justify-center items-center bg-transparent">
                                    <div v-if="step === 1" class="w-9/10">
                                        <h2>上传皮肤文件</h2>
                                        <input @change="onFileChange" :multiple="false" class="mt-2 file-input w-full" type="file" :disabled="s1_lock_a" />
                                        <h2 class="mt-2">或者…… 提供一个 NameMC 链接</h2>
                                        <input
                                            v-model="s1_input_b"
                                            class="mt-2 input w-full"
                                            placeholder="https://namemc.com/skin/... 或 https://zh.namemc.com/skin/..."
                                            :disabled="s1_lock_b" />
                                    </div>
                                    <div v-if="step === 2" class="w-9/10">
                                        <h2>这是你要的皮肤吗？</h2>
                                        <h2>如果是，请输入你的 ID</h2>
                                        <input v-model="s2_input" class="mt-2 input w-full" placeholder="例如: LingyunAwA" />
                                    </div>
                                    <div v-if="step === 3" class="w-9/10 flex items-center justify-center">
                                        <span class="loading loading-bars loading-xl scale-200"></span>
                                    </div>
                                    <div v-if="step === 4" class="w-9/10">
                                        <div role="alert" class="alert alert-error" v-if="!s4_success">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
                                                <path
                                                    stroke-linecap="round"
                                                    stroke-linejoin="round"
                                                    stroke-width="2"
                                                    d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>
                                            <span>{{ s4_fail_msg }}</span>
                                        </div>
                                        <section v-if="s4_success" class="w-full flex flex-col">
                                            <div role="alert" class="alert alert-success">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
                                                    <path
                                                        stroke-linecap="round"
                                                        stroke-linejoin="round"
                                                        stroke-width="2"
                                                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                </svg>
                                                <span>上传成功</span>
                                            </div>
                                            <button class="btn btn-primary mt-2 ml-auto" v-if="s4_success" @click="copyCmd">复制命令</button>
                                        </section>
                                    </div>
                                </section>

                                <section class="px-7 w-full flex justify-between items-center">
                                    <button class="btn btn-neutral" :disabled="step !== 2" @click="previousStep">返回</button>
                                    <button
                                        class="btn btn-primary ml-auto"
                                        :disabled="!((step === 1 && s1_valid) || (step === 2 && s2_valid) || step === 4)"
                                        @click="nextStep">
                                        {{ step === 4 ? "重置" : "确认" }}
                                    </button>
                                </section>
                            </div>
                        </div>
                    </div>
                </WrappedAnimatedContent>
            </div>
        </div>
    </div>
    <div class="card w-full h-3/5 bg-base-100 flex flex-col justify-center items-center gap-2 lg:hidden">
        <h1 class="text-3xl font-bold">提示</h1>
        <p class="text-xl">请使用电脑端访问工具箱</p>
    </div>
</template>

<style scoped>
    input {
        outline: none;
    }
</style>
