// components/mc521/tools/skin-view-3d.tsx
"use client";

import { useEffect, useRef } from "react";
import { IdleAnimation, SkinViewer } from "skinview3d";

interface SkinView3DProps {
    skin: string | null;
    className?: string;
}

export function SkinView3D({ skin, className }: SkinView3DProps) {
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const viewerRef = useRef<SkinViewer | null>(null);

    useEffect(() => {
        if (!canvasRef.current) return;

        const viewer = new SkinViewer({
            canvas: canvasRef.current,
            width: canvasRef.current.clientWidth,
            height: canvasRef.current.clientHeight,
        });
        viewer.zoom = 0.75;
        viewer.animation = new IdleAnimation();
        viewer.autoRotate = true;
        viewer.autoRotateSpeed = 0.8;
        viewerRef.current = viewer;

        const handleResize = () => {
            if (!canvasRef.current || !viewerRef.current) return;
            const { clientWidth, clientHeight } = canvasRef.current;
            viewerRef.current.setSize(clientWidth, clientHeight);
        };

        window.addEventListener("resize", handleResize);

        return () => {
            window.removeEventListener("resize", handleResize);
            viewer.dispose();
            viewerRef.current = null;
        };
    }, []);

    useEffect(() => {
        const viewer = viewerRef.current;
        if (!viewer) return;

        if (!skin) {
            viewer.loadSkin(null);
            return;
        }

        viewer.loadSkin(skin).catch(() => {
            // 加载失败时清空
            viewer.loadSkin(null);
        });
    }, [skin]);

    return <canvas ref={canvasRef} className={className} />;
}

// .vitepress/theme/components/SkinView3D.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from "vue";
import { SkinViewer, IdleAnimation } from "skinview3d";

const props = defineProps<{
    skin: string | null;
}>();

const canvasRef = ref<HTMLCanvasElement | null>(null);
let viewer: SkinViewer | null = null;

function createViewer(canvas: HTMLCanvasElement): SkinViewer {
    const instance = new SkinViewer({
        canvas,
        width: 320,
        height: 400,
        enableControls: true,
        zoom: 0.6,
    });

    instance.animation = new IdleAnimation();
    instance.animation.speed = 0.8;
    instance.autoRotate = true;
    instance.autoRotateSpeed = 0.6;
    instance.controls.enableZoom = false;
    instance.controls.enablePan = false;

    return instance;
}

function loadSkinSource(source: string | null): void {
    if (!viewer) return;
    if (source === null) {
        viewer.loadSkin(null);
        return;
    }
    viewer.loadSkin(source);
}

onMounted(() => {
    if (!canvasRef.value) return;
    viewer = createViewer(canvasRef.value);
    if (props.skin) {
        loadSkinSource(props.skin);
    }
});

onUnmounted(() => {
    viewer?.dispose();
    viewer = null;
});

watch(
    () => props.skin,
    (newSkin) => {
        loadSkinSource(newSkin);
    },
);
</script>

<template>
    <div class="skin-view-3d">
        <canvas ref="canvasRef" class="skin-canvas" />
    </div>
</template>

<style scoped>
.skin-view-3d {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: var(--space-4);
    background: rgba(0, 0, 0, 0.25);
    border-radius: var(--radius-md);
}

.skin-canvas {
    max-width: 100%;
    height: auto;
    border-radius: var(--radius-sm);
}
</style>
